##Installing PyTorch


In [0]:
!pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl

In [0]:
!pip3 install torchvision

## Importing Pytorch

In [0]:
from __future__ import print_function


In [0]:
import torch

In [0]:
import numpy as np

## PyTorch Tutorials

## [Deep Learning with PyTorch: A 60 Minute Blitz > What is PyTorch?](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)




In [0]:
#Tensor criado com valores(lixo) existentes nas posições de memória.

x = torch.empty(5, 3)
print(x)

tensor([[2.5875e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [0]:
#Tensor criado com valores aleatórios.

x = torch.rand(5,3)
print(x)

tensor([[0.9884, 0.6153, 0.9924],
        [0.9559, 0.5970, 0.1662],
        [0.3431, 0.0211, 0.2202],
        [0.2103, 0.8673, 0.5789],
        [0.8567, 0.5681, 0.0870]])


In [0]:
#Tensor criado com valores aleatórios inteiros.

x = torch.randint(0, 10, (5,3), dtype=torch.long)
print(x)

tensor([[4, 5, 2],
        [0, 4, 9],
        [1, 7, 6],
        [2, 2, 8],
        [7, 8, 8]])


In [0]:
#Tensor criado com zeros.

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
#Tensor criado com zeros.
#Este tensor possui 5 linhas, 3 colunas, e profundidade igual a 2.
#No caso do PyTorch, a profundidade do tensor é indicada na primeira posição da
#tupla, no caso o 2. A segunda posição é referente ao número de linhas(5) e a
#terceira posição é referente ao número de colunas(3).

x = torch.zeros(2, 5, 3, dtype=torch.long)
print(x)

print("     ")

#A função size() retorna as dimensões do tensor como a profundidade, número de
#linhas e número de colunas.

size = x.size()
print(size)


tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])
     
torch.Size([2, 5, 3])


In [0]:
#Exemplo para criação de um tensor com valores customizados.

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
#Exemplo para criação de um tensor com valores customizados.

x = torch.tensor([[0,1,0],
                  [1,0,1],
                  [0,1,0]])
print(x)

tensor([[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]])


In [0]:
#As operações de adição podem ser feitas de diversas formas.
#A seguir algumas dessas formas serão ilustradas

x = torch.tensor([[1,2,3],
                  [2,2,2],
                  [4,5,6]], dtype=torch.long)

y = torch.tensor([[1,1,1],
                  [0,0,0],
                  [1,1,1]], dtype=torch.long)

z = torch.tensor([[1,0,0],
                  [0,1,0],
                  [0,0,1]], dtype=torch.long)

w = torch.tensor([[12,23,32],
                  [22,21,25],
                  [42,58,66]], dtype=torch.long)

#PRIMEIRA FORMA

result = x + y
print(result)
print("\n")

#SEGUNDA FORMA

result = torch.add(x,y)
print(result)
print("\n")

#TERCEIRA FORMA

#Nesta maneira de adição, a variável(result) que irá armazenar o tensor 
#resultante da adição pode ser passada como parâmetro na função torch.add()
#após ter sido criada.

result = torch.empty(3,3, dtype=torch.long)
torch.add(x,y, out=result)
print(result)
print("\n")

#QUARTA FORMA

#Soma "x" à "y".
#Adição in-place, "x" é adicionado à "y" e o resultado é armazenado em "y".

y.add_(x)
print(y)
print("\n")

#EXTRA!!

#Cópia in-place, "z" é copiado para "y".
x.copy_(z)
print(x)
print("\n")

#Segue as mesmas regras do NumPy-Like Indexing.
#https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/
print(w[:,1])


tensor([[2, 3, 4],
        [2, 2, 2],
        [5, 6, 7]])


tensor([[2, 3, 4],
        [2, 2, 2],
        [5, 6, 7]])


tensor([[2, 3, 4],
        [2, 2, 2],
        [5, 6, 7]])


tensor([[2, 3, 4],
        [2, 2, 2],
        [5, 6, 7]])


tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])


tensor([23, 21, 58])


In [0]:
#Resizing/Reshape tensores

x_resized = torch.randn(4, 4)
print(x_resized)
print("\n")

y_resized = x_resized.view(16)
print(y_resized)
print("\n")

print(x_resized.size(), y_resized.size())

tensor([[-0.8850,  1.0184, -0.5328,  0.4798],
        [-0.9127,  0.1330,  0.6340,  0.0500],
        [-0.7817,  0.6811,  0.4191, -0.9660],
        [-0.6624,  3.0801, -1.3735, -1.0975]])


tensor([-0.8850,  1.0184, -0.5328,  0.4798, -0.9127,  0.1330,  0.6340,  0.0500,
        -0.7817,  0.6811,  0.4191, -0.9660, -0.6624,  3.0801, -1.3735, -1.0975])


torch.Size([4, 4]) torch.Size([16])


In [0]:
#Se houver apenas um valor no tensor pode-se usar a função item()
#para pegar o valor como um escalar em python. Caso haja mais de um
#um valor, acessa-se o valor usando "array[índice]" seguido de "item()".

tensor1 = torch.tensor([31])
print(tensor1)
tensor2 = torch.tensor([43,45,67])
print(tensor2)

valor1 = tensor1.item()

valor2 = tensor2[1].item()

valor3 = tensor2.size(0)

print(valor1)
print(valor2)
print(valor3)

tensor([31])
tensor([43, 45, 67])
31
45
3


In [0]:
#Convertendo um tensor Torch para um array NumPy.

x = torch.ones(5)
print(x)

w = torch.randn(4, 4)
z = w.numpy()
w.add_(1)
print(w)
print(z)

y = x.numpy()
print(y)

x.add_(1)
print(x)
print(y)

tensor([1., 1., 1., 1., 1.])
tensor([[ 2.3022,  0.2261,  1.2127, -0.3578],
        [ 2.7493,  1.9578,  1.7834,  1.3701],
        [ 0.4399,  0.8564, -0.1218,  0.4142],
        [-0.2102,  0.3166,  0.9009, -0.2138]])
[[ 2.3022032   0.22608805  1.2126986  -0.35775316]
 [ 2.7492623   1.957829    1.783438    1.3700507 ]
 [ 0.43985015  0.8563778  -0.12180352  0.41424745]
 [-0.21022284  0.31657964  0.90092486 -0.21382606]]
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
#Convertendo um array NumPy para um tensor Torch.

a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

np.add(a, 1, out=a)
print(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
#Verifica se há GPU disponível

print(torch.cuda.is_available())

True


In [0]:
#Verifica se a GPU está disponível e em caso afirmativo
#roda o bloco de código dentro da condição if.

x = torch.tensor([[1,2,3],
                  [2,2,2],
                  [4,5,6]], dtype=torch.long)

m = torch.tensor([[1,1,1],
                  [0,0,0],
                  [1,1,1]], dtype=torch.long)

if torch.cuda.is_available():
    device = torch.device("cuda")          
    y = torch.ones_like(x, device=device)
    x = x.to(device)                       
    z = x + y
    
    print(z)
    
    #Coloca o tenso "z" que estava na GPU novamente na CPU
    #e muda o tipo dos elementos para double.
    
    print(z.to("cpu", torch.double)) 

tensor([[2, 3, 4],
        [3, 3, 3],
        [5, 6, 7]], device='cuda:0')
tensor([[2., 3., 4.],
        [3., 3., 3.],
        [5., 6., 7.]], dtype=torch.float64)


In [0]:
#Testando divisão por zero, a qual  PyTorch não trata.
#Solução: somar 0.01 à matriz que irá dividir, no caso "m".

x = torch.tensor([[1,2,3],
                  [2,2,2],
                  [4,5,6]], dtype=torch.float)

m = torch.tensor([[0,0,0],
                  [0,0,0],
                  [0,0,0]], dtype=torch.float)


m.add_(0.01)

y = x/m

print(y)

tensor([[100., 200., 300.],
        [200., 200., 200.],
        [400., 500., 600.]])
